name: Ideagasms
favicon: null
layout_spectrum: 0.7846556312870234
typography_spectrum: 0.35543587477877736
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.49208083166740835
  lightness: 0.31259765289723873
  saturation: 0.1610791354905814
  rhythmicContrast: 0.21015238156542182
purpose: []
